/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes/index'
import { Route as ProgrammesCleanDivineIndiaRouteImport } from './routes/programmes/clean-divine-india'
import { Route as ProgrammesRaviKiranRouteImport } from './routes/programmes/ravi-kiran'
import { Route as ProgrammesTravelPartnershipsRouteImport } from './routes/programmes/travel-partnerships'
import { Route as ProgrammesWolooRouteImport } from './routes/programmes/woloo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCleanDivineIndiaRoute =
  ProgrammesCleanDivineIndiaRouteImport.update({
    id: '/programmes/clean-divine-india',
    path: '/programmes/clean-divine-india',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesRaviKiranRoute = ProgrammesRaviKiranRouteImport.update({
  id: '/programmes/ravi-kiran',
  path: '/programmes/ravi-kiran',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesTravelPartnershipsRoute =
  ProgrammesTravelPartnershipsRouteImport.update({
    id: '/programmes/travel-partnerships',
    path: '/programmes/travel-partnerships',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgrammesWolooRoute = ProgrammesWolooRouteImport.update({
  id: '/programmes/woloo',
  path: '/programmes/woloo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/journey': typeof JourneyRoute
  '/partner': typeof PartnerRoute
  '/programmes/clean-divine-india': typeof ProgrammesCleanDivineIndiaRoute
  '/programmes/ravi-kiran': typeof ProgrammesRaviKiranRoute
  '/programmes/travel-partnerships': typeof ProgrammesTravelPartnershipsRoute
  '/programmes/woloo': typeof ProgrammesWolooRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/journey': typeof JourneyRoute
  '/partner': typeof PartnerRoute
  '/programmes/clean-divine-india': typeof ProgrammesCleanDivineIndiaRoute
  '/programmes/ravi-kiran': typeof ProgrammesRaviKiranRoute
  '/programmes/travel-partnerships': typeof ProgrammesTravelPartnershipsRoute
  '/programmes/woloo': typeof ProgrammesWolooRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/impact': typeof ImpactRoute
  '/journey': typeof JourneyRoute
  '/partner': typeof PartnerRoute
  '/programmes/clean-divine-india': typeof ProgrammesCleanDivineIndiaRoute
  '/programmes/ravi-kiran': typeof ProgrammesRaviKiranRoute
  '/programmes/travel-partnerships': typeof ProgrammesTravelPartnershipsRoute
  '/programmes/woloo': typeof ProgrammesWolooRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/impact'
    | '/journey'
    | '/partner'
    | '/programmes/clean-divine-india'
    | '/programmes/ravi-kiran'
    | '/programmes/travel-partnerships'
    | '/programmes/woloo'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/impact'
    | '/journey'
    | '/partner'
    | '/programmes/clean-divine-india'
    | '/programmes/ravi-kiran'
    | '/programmes/travel-partnerships'
    | '/programmes/woloo'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/impact'
    | '/journey'
    | '/partner'
    | '/programmes/clean-divine-india'
    | '/programmes/ravi-kiran'
    | '/programmes/travel-partnerships'
    | '/programmes/woloo'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ImpactRoute: typeof ImpactRoute
  JourneyRoute: typeof JourneyRoute
  PartnerRoute: typeof PartnerRoute
  ProgrammesCleanDivineIndiaRoute: typeof ProgrammesCleanDivineIndiaRoute
  ProgrammesRaviKiranRoute: typeof ProgrammesRaviKiranRoute
  ProgrammesTravelPartnershipsRoute: typeof ProgrammesTravelPartnershipsRoute
  ProgrammesWolooRoute: typeof ProgrammesWolooRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/clean-divine-india': {
      id: '/programmes/clean-divine-india'
      path: '/programmes/clean-divine-india'
      fullPath: '/programmes/clean-divine-india'
      preLoaderRoute: typeof ProgrammesCleanDivineIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/ravi-kiran': {
      id: '/programmes/ravi-kiran'
      path: '/programmes/ravi-kiran'
      fullPath: '/programmes/ravi-kiran'
      preLoaderRoute: typeof ProgrammesRaviKiranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/travel-partnerships': {
      id: '/programmes/travel-partnerships'
      path: '/programmes/travel-partnerships'
      fullPath: '/programmes/travel-partnerships'
      preLoaderRoute: typeof ProgrammesTravelPartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/woloo': {
      id: '/programmes/woloo'
      path: '/programmes/woloo'
      fullPath: '/programmes/woloo'
      preLoaderRoute: typeof ProgrammesWolooRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ImpactRoute: ImpactRoute,
  JourneyRoute: JourneyRoute,
  PartnerRoute: PartnerRoute,
  ProgrammesCleanDivineIndiaRoute: ProgrammesCleanDivineIndiaRoute,
  ProgrammesRaviKiranRoute: ProgrammesRaviKiranRoute,
  ProgrammesTravelPartnershipsRoute: ProgrammesTravelPartnershipsRoute,
  ProgrammesWolooRoute: ProgrammesWolooRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
